---
apiVersion: v1
kind: Namespace
metadata:
  name: demo2-meshes-web
  labels:
    getkonvoy.io/sidecar-injection: enabled

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: demo2-meshes-web
data:
  kong.yml: |
    _format_version: "1.1"

    services:
    - name: mockbin.org
      url: http://mockbin.org
      routes:
      - name: default
        paths:
        - /
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: demo2-meshes-web
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8000
  selector:
    app: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-service-account
  namespace: demo2-meshes-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo2-meshes-web
  labels:
    app: web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: web-service-account
      containers:
      - name: web
        image: "kong:1.1.2-alpine"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: KONG_ADMIN_LISTEN
          value: "off"
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/etc/kong/kong.yml"
        volumeMounts:
        - name: web-config
          mountPath: /etc/kong
        livenessProbe:
          exec:
            command:
            - curl
            - -s
            - http://localhost:8000
        readinessProbe:
          exec:
            command:
            - curl
            - -s
            - http://localhost:8000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: web-config
        configMap:
          name: web-config
