version: '3.5'
services:

  konvoy-control-plane:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-cp
    command:
    - run
    volumes:
      - ./konvoy-control-plane/config.yaml:/etc/konvoy-control-plane/config.yaml
    expose:
      - "5678"
      - "5679"
      - "5680"
      - "5681"
    ports:
      - "15678:5678"
      - "15679:5679"
      - "15680:5680"
      - "15681:5681"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.1
        aliases:
        - konvoy-control-plane
    restart: on-failure

  backend-01:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-dp
    environment:
    - KONVOY_CONTROL_PLANE_XDS_SERVER_ADDRESS=konvoy-control-plane
    - KONVOY_CONTROL_PLANE_XDS_SERVER_PORT=5678
    - KONVOY_DATAPLANE_ID=backend-01
    - KONVOY_DATAPLANE_SERVICE=backend
    - KONVOY_DATAPLANE_ADMIN_PORT=9901
    command:
    - run
    expose:
      - "9901"
    ports:
      - "19901:9901"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.10
        aliases:
          - backend-01
    depends_on:
      - konvoy-control-plane
    restart: on-failure

  backend-02:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-dp
    environment:
    - KONVOY_CONTROL_PLANE_XDS_SERVER_ADDRESS=konvoy-control-plane
    - KONVOY_CONTROL_PLANE_XDS_SERVER_PORT=5678
    - KONVOY_DATAPLANE_ID=backend-02
    - KONVOY_DATAPLANE_SERVICE=backend
    - KONVOY_DATAPLANE_ADMIN_PORT=9901
    command:
    - run
    expose:
      - "9901"
    ports:
      - "29901:9901"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.11
        aliases:
          - backend-02
    depends_on:
      - konvoy-control-plane
    restart: on-failure

  web-01:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-dp
    environment:
    - KONVOY_CONTROL_PLANE_XDS_SERVER_ADDRESS=konvoy-control-plane
    - KONVOY_CONTROL_PLANE_XDS_SERVER_PORT=5678
    - KONVOY_DATAPLANE_ID=web-01
    - KONVOY_DATAPLANE_SERVICE=web
    - KONVOY_DATAPLANE_ADMIN_PORT=9901
    command:
    - run
    expose:
      - "9901"
    ports:
      - "39901:9901"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.20
        aliases:
          - web-01
    depends_on:
      - konvoy-control-plane
    restart: on-failure

  mobile-01:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-dp
    environment:
    - KONVOY_CONTROL_PLANE_XDS_SERVER_ADDRESS=konvoy-control-plane
    - KONVOY_CONTROL_PLANE_XDS_SERVER_PORT=5678
    - KONVOY_DATAPLANE_ID=mobile-01.default.pilot
    - KONVOY_DATAPLANE_SERVICE=mobile
    - KONVOY_DATAPLANE_ADMIN_PORT=9901
    command:
    - run
    expose:
      - "9901"
    ports:
      - "49901:9901"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.30
        aliases:
          - mobile-01
    depends_on:
      - konvoy-control-plane
    restart: on-failure

networks:
  demo2-universal:
    ipam:
      driver: default
      config:
       - subnet: 172.28.0.0/16
