version: '3.5'
services:

  konvoy-control-plane:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-cp
    command:
    - run
    volumes:
      - ./konvoy-control-plane/config.yaml:/etc/konvoy-control-plane/config.yaml
    expose:
      - "5678"
      - "5679"
      - "5680"
      - "5681"
    ports:
      - "15678:5678"
      - "15679:5679"
      - "15680:5680"
      - "15681:5681"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.1
        aliases:
        - konvoy-control-plane
    restart: on-failure

  backend-01:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-dp
    volumes:
      - ./run_konvoy_dp_with_echo.sh:/run_konvoy_dp_with_echo.sh
    environment:
    - KONVOY_CONTROL_PLANE_XDS_SERVER_ADDRESS=konvoy-control-plane
    - KONVOY_CONTROL_PLANE_XDS_SERVER_PORT=5678
    - KONVOY_DATAPLANE_ID=backend-01
    - KONVOY_DATAPLANE_SERVICE=backend
    - KONVOY_DATAPLANE_ADMIN_PORT=9901
    entrypoint:
    - /run_konvoy_dp_with_echo.sh
    - "Hi there! I'm backend-01"
    - "127.0.0.1:8081"
    expose:
      - "9901"
    ports:
      - "19901:9901"
      - "18080:8080"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.10
        aliases:
          - backend-01
    depends_on:
      - konvoy-control-plane
    restart: on-failure

  backend-02:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-dp
    volumes:
      - ./run_konvoy_dp_with_echo.sh:/run_konvoy_dp_with_echo.sh
    environment:
    - KONVOY_CONTROL_PLANE_XDS_SERVER_ADDRESS=konvoy-control-plane
    - KONVOY_CONTROL_PLANE_XDS_SERVER_PORT=5678
    - KONVOY_DATAPLANE_ID=backend-02
    - KONVOY_DATAPLANE_SERVICE=backend
    - KONVOY_DATAPLANE_ADMIN_PORT=9901
    entrypoint:
      - /run_konvoy_dp_with_echo.sh
      - "Hi there! I'm backend-02"
      - "127.0.0.1:8082"
    expose:
      - "9901"
    ports:
      - "29901:9901"
      - "28080:8080"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.11
        aliases:
          - backend-02
    depends_on:
      - konvoy-control-plane
    restart: on-failure

  web-01:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-dp
    volumes:
      - ./run_konvoy_dp_with_echo.sh:/run_konvoy_dp_with_echo.sh
    environment:
    - KONVOY_CONTROL_PLANE_XDS_SERVER_ADDRESS=konvoy-control-plane
    - KONVOY_CONTROL_PLANE_XDS_SERVER_PORT=5678
    - KONVOY_DATAPLANE_ID=web-01
    - KONVOY_DATAPLANE_SERVICE=web
    - KONVOY_DATAPLANE_ADMIN_PORT=9901
    entrypoint:
      - /run_konvoy_dp_with_echo.sh
      - "Hi there! I'm web-01"
      - "127.0.0.1:8082"
    expose:
      - "9901"
    ports:
      - "39901:9901"
      - "38080:8080"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.20
        aliases:
          - web-01
    depends_on:
      - konvoy-control-plane
    restart: on-failure

  mobile-01:
    build:
      context: ../../..
      dockerfile: Dockerfile.konvoy-dp
    volumes:
      - ./run_konvoy_dp_with_echo.sh:/run_konvoy_dp_with_echo.sh
    environment:
    - KONVOY_CONTROL_PLANE_XDS_SERVER_ADDRESS=konvoy-control-plane
    - KONVOY_CONTROL_PLANE_XDS_SERVER_PORT=5678
    - KONVOY_DATAPLANE_ID=mobile-01.default.pilot
    - KONVOY_DATAPLANE_SERVICE=mobile
    - KONVOY_DATAPLANE_ADMIN_PORT=9901
    entrypoint:
      - /run_konvoy_dp_with_echo.sh
      - "Hi there! I'm mobile-01"
      - "127.0.0.1:8083"
    expose:
      - "9901"
    ports:
      - "49901:9901"
      - "48080:8080"
    networks:
      demo2-universal:
        ipv4_address: 172.28.1.30
        aliases:
          - mobile-01
    depends_on:
      - konvoy-control-plane
    restart: on-failure

networks:
  demo2-universal:
    ipam:
      driver: default
      config:
       - subnet: 172.28.0.0/16
