---
apiVersion: v1
kind: Namespace
metadata:
  name: konvoy-demo
  labels:
    getkonvoy.io/sidecar-injection: enabled

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: konvoy-demo
data:
  kong.yml: |
    _format_version: "1.1"

    services:
    - name: mockbin.org
      url: http://mockbin.org
      routes:
      - name: default
        paths:
        - /
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: konvoy-demo
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: demo-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-service-account
  namespace: konvoy-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: konvoy-demo
  labels:
    app: demo-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: demo-app-service-account
      containers:
      - name: demo-app
        image: "kong:1.1.2-alpine"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: KONG_ADMIN_LISTEN
          value: "off"
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/etc/kong/kong.yml"
        volumeMounts:
        - name: demo-app-config
          mountPath: /etc/kong
        livenessProbe:
          exec:
            command:
            - curl
            - -s
            - http://localhost:8000
        readinessProbe:
          exec:
            command:
            - curl
            - -s
            - http://localhost:8000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: demo-app-config
        configMap:
          name: demo-app-config
